### ISSUE TITLE
Sparrow on WSL Windows 10

### ISSUE THREAD

**Issue by thefallingduck** [EarthCubeGeochron/Sparrow#12]
Can't set this up appears to be a problem with docker compose.

```
Attaching to sparrow_gateway_1, sparrow_frontend_1, sparrow_backend_1, sparrow_db_1
gateway_1   | 2019/10/10 18:48:39 [crit] 1#1: pread() "/etc/nginx/nginx.conf" failed (21: Is a directory)
gateway_1   | nginx: [crit] pread() "/etc/nginx/nginx.conf" failed (21: Is a directory)
frontend_1  | internal/modules/cjs/loader.js:670
frontend_1  |     throw err;
frontend_1  |     ^
frontend_1  |
frontend_1  | Error: Cannot find module '/app/run-docker'
frontend_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
frontend_1  |     at Function.Module._load (internal/modules/cjs/loader.js:591:27)
backend_1   | db:5432 - accepting connections
backend_1   | python3: can't open file 'sparrow': [Errno 2] No such file or directory
backend_1   | python3: can't open file 'sparrow': [Errno 2] No such file or directory
frontend_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
frontend_1  |     at internal/main/run_main_module.js:21:11
db_1        | 2019-10-10 18:48:33.548 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1        | 2019-10-10 18:48:33.548 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1        | 2019-10-10 18:48:33.596 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1        | 2019-10-10 18:48:33.669 UTC [22] LOG:  database system was shut down at 2019-10-10 18:48:31 UTC
db_1        | 2019-10-10 18:48:33.697 UTC [1] LOG:  database system is ready to accept connections
sparrow_gateway_1 exited with code 1
sparrow_backend_1 exited with code 2
sparrow_frontend_1 exited with code 1
```

**Comment by davenquinn** [comment]
This was off the feature/windows branch, we changed how the `nginx.conf` got loaded into docker because of these problems.

**Comment by davenquinn** [comment]
Hey @Idzikowski-Casey — you've solved this issue! Adding a Markdown document describing your setup in the `docs/docs` directory on Windows installation would be a good way to close this out. Then @thefallingduck can try his laptop at some point if he remains interested.
